#----------------------------------------
# GENERAL SETTINGS
#----------------------------------------

# Site title, appears in the browser tab.
title: "Patryk Dejewski"

# Site description in search engine.
description: "Hello. I’m interested in web development and web design. I like doing websites with Jekyll and designs in Figma and Inkscape. If you want to contact me, feel free to send an email."

# Language settings for html and seo
lang: "en_GB"
iso-lang: "en"

# Production url.
url: "https://vllur.github.io"

# Part after .com, etc. use / if none.
baseurl: /



#----------------------------------------
# CONTENT VARIABLES
#----------------------------------------

# Site header text
header: "Patryk Dejewski"

# Links
blog: https://vllur.github.io/blog/
github: https://github.com/vllur
linkedin: https://www.linkedin.com/in/patryk-dejewski/
mastodon: https://fosstodon.org/@vllur
mail: patryk.dejewski@disroot.org

# Posts, drafts and other collections in '_content' directory
collections_dir: content

# Projects collection
collections:
  projects:
  img:
    output: true
    permalink: /:collection/:name



#----------------------------------------
# JEKYLL SETTINGS
#----------------------------------------

# Takes files from root folder, generates site into ./_site.
source: .
destination: ./_site

# Default variables for pages. Are in use if not overwritten.
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Excluding dev gem builds from website.
exclude: [vendor]

# Jekyll plugins.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
